[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py --web"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"

[env]
PYTHONUNBUFFERED = "1"
PORT = "8000"

[[services]]
name = "truth-engine" 