name: Daily Data Refresh

on:
  schedule:
    # Run daily at 6:00 AM EST (11:00 UTC)
    - cron: '0 11 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate Daily Digest
      run: python main.py --run
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CONGRESS_API_KEY: ${{ secrets.CONGRESS_API_KEY }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        
    - name: Commit and Push Updated Data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git diff --staged --quiet || git commit -m "🔄 Daily data refresh - $(date +'%Y-%m-%d %H:%M UTC')"
        git push 