name: Test and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test OpenAI Connection
      run: python test_openai.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
    - name: Test Application
      run: python -m pytest test_analyzer.py -v
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CONGRESS_API_KEY: ${{ secrets.CONGRESS_API_KEY }}
        
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test Docker Build
      run: |
        docker build -t truth-engine .
        echo "✅ Docker build successful!" 