name: Deploy to Railway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Railway CLI
      run: npm install -g @railway/cli
      
    - name: Deploy to Railway
      run: railway up --service=${{ secrets.RAILWAY_SERVICE_NAME || 'truth-engine' }}
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CONGRESS_API_KEY: ${{ secrets.CONGRESS_API_KEY }}
        
    - name: Set Railway Environment Variables
      run: |
        railway variables set OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" --service=${{ secrets.RAILWAY_SERVICE_NAME || 'truth-engine' }}
        railway variables set CONGRESS_API_KEY="${{ secrets.CONGRESS_API_KEY }}" --service=${{ secrets.RAILWAY_SERVICE_NAME || 'truth-engine' }}
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test OpenAI Connection
      run: python test_openai.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
    - name: Test Application
      run: python -m pytest test_analyzer.py -v
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CONGRESS_API_KEY: ${{ secrets.CONGRESS_API_KEY }} 